import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    ignores: [
      'dist/**',
      'node_modules/**',
      'src-tauri/target/**',
      'extensions/**',
      'src/vscode-dts/**',
      'src/typings/**',
      '**/test/**/fixtures/**',
    ],
  },
  {
    files: ['**/*.ts', '**/*.tsx'],
    extends: [tseslint.configs.recommended],
    rules: {
      curly: 'warn',
      eqeqeq: ['warn', 'always', { null: 'ignore' }],
      'prefer-const': ['warn', { destructuring: 'all' }],
      'no-caller': 'warn',
      'no-debugger': 'warn',
      'no-duplicate-imports': 'off',
      'no-eval': 'warn',
      'no-new-wrappers': 'warn',
      'no-throw-literal': 'warn',
      'no-var': 'warn',
      'no-restricted-globals': [
        'warn',
        'name',
        'length',
        'event',
        'closed',
        'status',
        'origin',
      ],
      'prefer-rest-params': 'off',
      'prefer-spread': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-unused-vars': [
        'warn',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
      '@typescript-eslint/naming-convention': [
        'warn',
        { selector: 'class', format: ['PascalCase'] },
      ],
      '@typescript-eslint/no-namespace': 'off',
      '@typescript-eslint/no-this-alias': 'off',
      '@typescript-eslint/no-empty-object-type': 'off',
      '@typescript-eslint/ban-ts-comment': 'off',
      '@typescript-eslint/no-unsafe-declaration-merging': 'off',
      '@typescript-eslint/no-duplicate-enum-values': 'off',
      '@typescript-eslint/no-unused-expressions': 'off',
      '@typescript-eslint/prefer-as-const': 'warn',
      '@typescript-eslint/no-non-null-asserted-optional-chain': 'warn',
      '@typescript-eslint/no-require-imports': 'off',
    },
  },
  {
    files: ['**/*.cjs'],
    rules: {
      curly: 'warn',
      eqeqeq: 'warn',
      'no-caller': 'warn',
      'no-debugger': 'warn',
      'no-eval': 'warn',
      'no-var': 'warn',
    },
  },
);
